name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]
  # Allows manual runs in the Actions tab:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      # Needed to push to GHCR using GITHUB_TOKEN
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        env:
          # Dynamically build the image name from your repo slug (kelleyblackmore/ubuntu-hardened)
          IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
        run: |
          echo "Building and pushing $IMAGE_NAME..."
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Security Scan with Trivy (optional)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1"
          format: 'table'
